### ISSUE TITLE
Statement of Goals

### ISSUE THREAD

**Issue by bradley-holt** [janl/offlinefirst.org#13]
We should add a statement of our goals with this event early on in the event description. This could help people better understand what the event is all about and why they might want to participate. Here's a potential first draft:

> Offline Camp is an opportunity to bring together the growing Offline First community. We will be exploring the entire spectrum of Offline First including Progressive Web Apps, mobile apps (native and hybrid), desktop apps (e.g. Electron), and Internet of Things (IoT) apps. Offline Camp will be an open, participatory event. Please bring your perspective on Offline First and be willing to share—and listen!

**Comment by gr2m** [comment]
Yeah I agree! Can we incorporate UX / management perspectives into the text?

**Comment by bradley-holt** [comment]
Yes! It should also include a UX perspective. Maybe:

> Offline Camp is an opportunity to bring together the growing Offline First community. We will be exploring the entire spectrum of Offline First including Progressive Web Apps, mobile apps (native and hybrid), desktop apps (e.g. Electron), Internet of Things (IoT) apps, and the UX of Offline First in these various contexts. Offline Camp will be an open, participatory event. Please bring your perspective on Offline First and be willing to share—and listen!

How did you mean "management" in this context?

**Comment by gr2m** [comment]
With management I mean decision makers, people with perspective on what’s viable. I think the tech perspective is what’s possible and the UX perspective is what’s desirable by users, but in the end we also need to convince that there are business reasons for Offline First, too. I don’t know if this makes sense right now, it’s just me thinking out loud :D

**Comment by bradley-holt** [comment]
Got it. How about the following? Feel free to tweak/adjust as you see fit:

> Offline Camp is an opportunity to bring together the growing Offline First community. We will be exploring the entire spectrum of Offline First including Progressive Web Apps, mobile apps (native and hybrid), desktop apps (e.g. Electron), Internet of Things (IoT) apps, the business case for Offline First, and the UX of Offline First. Offline Camp will be an open, participatory event. Please bring your perspective on Offline First and be willing to share—and listen!

**Comment by gr2m** [comment]
I love it. @kidfribble what do you think?

**Comment by terichadbourne** [comment]
Added Bradley's last draft paragraph to the site.  Let me know if you feel other changes are needed.
