### ISSUE TITLE
Slack signup is broken on chat page

### ISSUE THREAD

**Issue by terichadbourne** [janl/offlinefirst.org#146]
http://offlinefirst.org/chat/

Instead of the normal bit about requesting a signup for Slack (with some Slack graphics) the "Chat" page is currently displaying 

404 Not Found
nginx/1.1.19

I'm not sure how to fix this one. Page says to ping @trodrigues (which I've also done on Twitter).

**Comment by trodrigues** [comment]
It's back up. Apologies for the issue.
