### ISSUE TITLE
Change search result title for Offline Camp page

### ISSUE THREAD

**Issue by terichadbourne** [janl/offlinefirst.org#168]
Let's figure out where to change the metadata so Offline Camp shows up in search engine results as "Offline Camp." 

If I search for Offline First events I see this "Camp - Offline First!"

![image](https://user-images.githubusercontent.com/19171465/29139942-ae07878c-7d16-11e7-84d6-d425cc6520c9.png)

If I search for Offline Camp I see "Offline Camp - Offline First!"

![image](https://user-images.githubusercontent.com/19171465/29139960-c889e640-7d16-11e7-87b8-b3dc8e97f2ca.png)

This problem may get solved while we're fixing issue #163

**Comment by terichadbourne** [comment]
Issue #163 is solved but this one isn't: 

![image](https://user-images.githubusercontent.com/19171465/29288893-93869038-8108-11e7-951a-dc87332648b6.png)

![image](https://user-images.githubusercontent.com/19171465/29288919-a4691150-8108-11e7-8b60-b144cfc06fae.png)

@gr2m @kidfribble @bradley-holt Any ideas on either: 
a) Why this wasn't solved by removing the exclamation point from the index HTML? (I had assumed these names with the hyphens were building themselves based on site structure.
b) Why in some search results offlinefirst.org/camp displays as  "Offline Camp - Offline First!" and in others it displays as "Camp - Offline First!" ? I prefer the former.

**Comment by bradley-holt** [comment]
@terichadbourne I believe this is because Google has re-indexed the homepage but not the camp page yet. If you look at the Google cache for each page (`cache:offlinefirst.org` and `cache:offlinefirst.org/camp/` you will see that the homepage cache is from `Aug 12, 2017 08:08:44 GMT` and the Offline Camp page cache is from `Aug 8, 2017 12:07:47 GMT`.

**Comment by terichadbourne** [comment]
Thanks @bradley-holt. Trying this tool again (https://www.google.com/webmasters/tools/submit-url) on the camp URL. 

Any theories on issue (b)?

**Comment by bradley-holt** [comment]
@terichadbourne Huh. That's strange. My best guess is that it's just a difference in which cached result Google is using. It will probably stay consistent after some period of time.

**Comment by terichadbourne** [comment]
I still see either "Camp" or "Offline Camp" before " - Offline First" depending on my search terms, but the exclamation point is now gone on both, so I'm marking this resolved.
