### ISSUE TITLE
Please provide RSS/Atom feed of Offline First News

### ISSUE THREAD

**Issue by felixc** [janl/offlinefirst.org#21]
It's currently possible to subscribe to http://offlinefirst.org/news/ by email, but it would be great to be able to subscribe to an RSS/Atom feed as well.

Not only is it some people's preferred way of getting updates, it's also a great offline experience :)

**Comment by gr2m** [comment]
does this work? http://us4.campaign-archive2.com/feed?u=12d36bbe9418ed6a43127cd62&id=7fc00bfaef It’s taken from Mailchimps email archive: http://us4.campaign-archive2.com/home/?u=12d36bbe9418ed6a43127cd62&id=7fc00bfaef

**Comment by felixc** [comment]
That works great; thank you!

It might be a good idea to add a link to it from the main "news" page, or even just a hidden `<link rel="alternate" type="application/rss+xml" href="http://us4.campaign-archive2.com/feed?u=12d36bbe9418ed6a43127cd62&id=7fc00bfaef">` so it can be autodiscovered by RSS/Atom reader clients. I for one had no idea this archive existed :)

**Comment by gr2m** [comment]
That’s a great idea, we can even add it to all pages. Could you send a pull request for it?

**Comment by felixc** [comment]
Will do. I'm thinking I'll add the hidden autodiscovery link to the News and the main landing page, as well as a visible link on the News page. Let me know if you'd prefer something different.
