### ISSUE TITLE
Chat Link 404

### ISSUE THREAD

**Issue by optikfluffel** [janl/offlinefirst.org#7]
The `<a href="chat.html">Offline First Chat</a>` [in index.html](https://github.com/offlinefirst/offlinefirst.org/blob/af4981c54465fa4f42cd695876821b79db635ee8/index.html#L89) 404s. Apart from that great work! :rocket:

**Comment by martinox** [comment]
This was fixed in commit 0a7e1b1bb1aa578fd6426f91fef335c629225afa

**Comment by janl** [comment]
thanks for the report tho!
